library("lubridate")
source('data.R')
png("plot2.png")
days <- dmy_hms(paste(data$Date, " ", data$Time))
with(data, plot(days, Global_active_power, type="n", xlab="", ylab="Global Active Power (killowatts)"))
with(data, lines(days, Global_active_power))
dev.off()