library("lubridate")
source('data.R')
png("plot4.png")
days <- dmy_hms(paste(data$Date, " ", data$Time))
par(mfrow=c(2,2))
with(data, plot(days, Global_active_power, type="n", xlab="", ylab="Global Active Power"))
with(data, lines(days, Global_active_power))
with(data, plot(days, Voltage, type="n", xlab="datetime", ylab="Voltage"))
with(data, lines(days, Voltage))
with(data, plot(days, Sub_metering_1, type="n", xlab="", ylab="Energy sub metering"))
with(data, lines(days, Sub_metering_1, col="black"))
with(data, lines(days, Sub_metering_2, col="red"))
with(data, lines(days, Sub_metering_3, col="blue"))
legend("topright", bty="n", lty = c(1,1,1), col = c("black", "red", "blue"), legend=c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"))
with(data, plot(days, Global_reactive_power, type="n", xlab="datetime"))
with(data, lines(days, Global_reactive_power))
dev.off()