library("lubridate")
source('data.R')
png("plot3.png")
days <- dmy_hms(paste(data$Date, " ", data$Time))
with(data, plot(days, Sub_metering_1, type="n", xlab="", ylab="Energy sub metering"))
with(data, lines(days, Sub_metering_1, col="black"))
with(data, lines(days, Sub_metering_2, col="red"))
with(data, lines(days, Sub_metering_3, col="blue"))
legend("topright", lty = c(1,1,1), col = c("black", "red", "blue"), legend=c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"))
dev.off()